# resolver: nightly-2024-12-20 # ghc-9.10.1
resolver: lts-23.1 # ghc-9.8.4
# resolver: lts-22.43  # ghc-9.6.6
# resolver: lts-22.27  # ghc-9.6.5
# resolver: lts-21.25 # ghc-9.4.8
# resolver: lts-20.26 # ghc-9.2.8
# resolver: lts-19.0 # ghc-9.0.2
# resolver: lts-18.28 # ghc-8.10.7
# resolver: lts-18.6 # ghc-8.10.4 # Currently the only version that seems to work with LiquidHaskell
packages:
  - .
allow-newer: true
extra-deps:
  # For Posit:
  - posit-2022.2.0.1
  - cl3-3.0.0.0 # cl3 should also compile using Doubles
  # For Massiv benchmarks:
  - massiv-1.0.4.0
  - scheduler-2.0.0

  # For LiquidHaskell:
  # - hashable-1.3.5.0 # lts-20.16 and below
  # hashable-1.4.2.0 # ghc-9.4.4 and above
  - hashable-1.4.3.0 # ghc-9.8.1 and above
  - text-format-0.3.2
  - Diff-0.3.4
  # - optparse-applicative-0.16.1.0
  # - rest-rewrite-0.3.0 # ye olde reliable
  - rest-rewrite-0.4.1 # latest
  - smtlib-backends-0.3 # ghc-9.2.7
  - smtlib-backends-process-0.3 # ghc-9.2.7
  - git: https://github.com/ucsd-progsys/liquidhaskell 
    # commit: <something> # ghc-9.4.4 "Generically" errors out! Ambiguous occurrence ‘Generically’: It could refer to... ‘GHC.Generics.Generically’ or 'Language.Haskell.Liquid.Types.Generics.Generically'
    commit: 63337d432b47c1ba1ec9925db0994fc5cdce3eaf # 98eaf04d8c4be89924e025c8e982e54bce457643 #  ghc-9.2.7
    # commit: b8780ee8d73d123adb39675ef87a2883f8aa1ecd # ghc-9.0.2
    # commit: f917323a1f9db1677e592d6ffc81467d53588d70 # ghc-8.10.7
    subdirs:
      - .
      - liquid-vector
      - liquid-bytestring
      - liquid-containers
      - liquid-ghc-prim 
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 0e1a4725793740f495c26957044c56488d6e1efc # ghc-9.2.7
    # commit: 5aed39ec3210b9093ed635693d01bf351e25392f # ghc-9.0.2
    # commit: 544f8b0ba6d03b060701961250cce012412039c4 # ghc-8.10.7

